parser: babel-eslint

plugins:
  - no-loops
  - react
  - react-functional-set-state

env:
  browser: true
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  array-bracket-spacing: error
  block-spacing:
    - error
    - always
  camelcase:
    - error
    - properties: never
  capitalized-comments: error
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style: error
  eqeqeq: error
  func-style:
    - error
    - expression
  indent:
    - 2
    - 2
  init-declarations: error
  jsx-quotes:
    - error
    - prefer-single
  keyword-spacing:
    - error
    - after: true
      before: true
  linebreak-style:
    - error
    - unix
  newline-after-var:
    - error
    - always
  no-alert: error
  no-debugger: error
  no-else-return: error
  no-loops/no-loops: 2
  no-magic-numbers:
    - error
    - ignore: [-1, 0, 1]
  no-multiple-empty-lines:
    - error
    - max: 1
  no-native-reassign: error
  no-negated-condition: error
  no-tabs: error
  no-trailing-spaces: error
  no-useless-return: error
  no-var: error
  react-functional-set-state/no-this-state-props: error
  semi:
    - error
    - never
  space-before-blocks: error
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  quotes:
    - error
    - single
