parser: babel-eslint

plugins:
  - react

env:
  browser: true
  node: true
  es6: true

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  comma-spacing:
    - error
    - after: true
      before: false
  indent:
    - 2
    - 2
  semi:
    - error
    - never
  quotes:
    - error
    - single
